
# Introduction    

The development of civic values and attitudes of tolerance and respect for the rights of diverse social groups among youth is essential for sustainable democratic societies. These values are strongly promoted by families, educational systems, and international organizations across the world. The measurements and comparison of these attitudes among youth can provide valuable information about their development in different societies.  

International studies such as the International Civic and Citizenship Education Study (ICCS)[^1] [@wolfram_schulz_iccs_2018]  provide extensive and unique comparative information regarding these aspects. The ICCS study is a large-scale assessment (survey) applied in more than 25 educational systems during the last three cycles (1999, 2009, 2016) and focused on secondary education (representative samples of 8th graders, 14-year-olds in each country) addressing topics such as citizenship, diversity, and social interactions at school. 

[^1]: https://www.iea.nl/studies/iea/iccs  

International and national ICCS study reports as well as previous empirical research using ICCS data have been largely focused on average country comparisons of attitudinal measures such as attitudes toward equal rights for immigrants, ethnic minorities and women, norms of good citizenship behavior and political participation. Most of these studies employed variable-centered analyses such as factor analysis and were able to provide valuable comparative information regarding average attitudinal levels in different societies (i.e., tapping into the overall tendency of respondents to indicate a higher response category when rating a set of items).  Nevertheless, the variable-centered approach is less useful when researchers, driven by theoretical assumptions, aim to identify the most likely patterns of responses by participants. Indeed, some recent studies applied to ICCS data started to show the usefulness of person-centered approaches (i.e., latent class analysis, hereafter LCA) aimed at identifying profiles of young people’s attitudes. For example, using ICCS 2009 data, [@hooghe_comparative_2016; @barber_profiles_2020] build on political science theories of good citizenship norms to compare profiles of good citizenship norms across 38 countries and distinguished distinctive subgroups of the population that share a common understanding of what constitutes good citizenship were identified (e.g., who express either engaged or duty-based citizenship norms).  

Nevertheless, such studies (i.e., employing LCA with ICCS data and focusing on patterns within a particular type of attitude described by individual items) are still scarce. This is especially true for the fields of educational and political sciences and particularly when cross-country comparisons are involved. Indeed, this scarcity of empirical studies employing LCA can be linked to some extent to disciplinary traditions favoring variable-centered approaches but most importantly to the novelty and complexity of LCA in these disciplines especially when cross-cultural comparability (i.e., measurement invariance) must be evaluated and ensured. 

In this thesis I aim to address this gap by providing a comprehensive overview of LCA and its application to international large-scale assessment (ILSA) data and by illustrating the procedure to conduct LCA (including measurement invariance testing in LCA) using R and Mplus with a step-by-step example. As a substantive background to this example, I approach a topic of high societal relevance, young people’s attitudes of tolerance and respect for the rights of different and often marginalized groups such as ethnic minorities and women. More specifically, I focus on the operationalization of these attitudes in the ICCS 2016 study’s international student questionnaire: a) young people’s attitudes toward equal rights for women and b) young people’s attitudes toward equal rights for ethnic/race groups. Moreover, I apply LCA to a heterogeneous (in terms of linguistic, geographic, economic and social contexts) sample of 14 European countries participating in ICCS 2016 with the aim of answering the following research questions:    

- What profiles of attitudes towards gender equality are identified among adolescents in the 14 European countries?  
- What profiles of tolerance and respect for equal rights of ethnic/race groups are observed among adolescents in the 14 European countries?   
- Are these two sets of profiles fully comparable/measurement invariant across the 14 European countries?    

With this analysis, this thesis aims to contribute to the current state-of-the art in both substantive and procedural ways. On the substantive side, I intend to add to the body of research focused on young people’s attitudes of tolerance and respect for the rights of ethnic groups and women by pointing out information that is not reported in extent research. More specifically, unlike previous research that illustrated average attitudinal differences among countries (e.g., showing that on average adolescents tend to tolerant), this study is able to point out response’s patterns within a particular type of attitude described by individual items (e.g., distinguishing between different groups adolescents with particular sets of views). On the procedural side, I aim to facilitate, for a wider group of scholars, the application of LCA to ILSA data with a comprehensive description of the statistical method and an easy to replicate, step-by-step procedure for its implementation in R and Mplus. 

\newpage  

#### Overview of this thesis

Including this introduction, this thesis consists of five chapters and an appendix.  

In the second chapter, I introduce the features of ILSAs, the ICCS 2016 study, and the background for the example used in this research. This chapter also includes an overview of LCA in comparison to person-centered methods and details different approaches to measurement invariance in LCA.  

The third chapter describes the methodology applied in this research including the analytical approaches, the characteristics of the sample, and the study’s measurement instruments.    

Chapter four illustrates the results concerning the two main topics analyzed: a) young people’s attitudes toward equal rights for women, and b) young people’s attitudes toward equal rights for ethnic/race groups. Different sets of results concerning country-specific analysis and cross-country comparability are reported.  

Finally, a discussion of the findings is provided in chapter five and the appendix includes detailed supplementary information regarding the methods and results and the detailed syntax and output examples.
 

\clearpage