# Discussion and conclusion  



An important amount of studies have been performed in previous years addressing the comparability of attitudes towards different minorities groups but mainly based on a variable centered approach which provides valuable information on the country's average profile but it does not identify patterns (subpopulations) within countries. The main focus of this thesis was to identify different comparable patterns of students' attitudes of tolerance and respect for the rights of diverse social groups, particularly women and ethnic and racial groups. The research questions in this study were based on exploring the different possible profiles of students that could be found and if their comparability across countries were possible, in both Students' endorsement of gender equality and Students' endorsement of equal rights for all ethnic/racial groups scales from ICCS 2016 study.  



In order to achieve this goal, the most suitable methodology is Latent Class Analysis, a person-centered approach that by using a mixture model that considers different distributions can identify heterogeneous groups. An exploratory approach was implemented along with the study of invariance across 14 European countries. A confirmatory model was tested in order to provide more insightful patterns. 



The person-centered approach gives the possibility to explore the different profiles that can be identified using the individual items that were used by the consortium to create the country's average validated indicators. Together with this, now it is not only possible to compare the countries' average level of the students' attitudes toward equal rights but it is also possible to learn how each country's population is composed, by subgroups of students' attitudes or patterns and compare them. Latent Class Analysis is a great tool for identifying these profiles based on a statistical approach, with tests and statistics that give strong evidence to state why those profiles were identified.  



Despite the complexity of identifying reliable and interpretable profiles for the representative samples, the analysis provided strong evidence to identify the most common profiles across countries. Model fit statistics are of great help to provide statistical evidence to reject models that do not fit properly the data. In this research, it was a tendency that model fit statistic AIC tended to overfit the data, in most of the cases model fit statistics accepted a model but AIC would prefer a model with one more class.  



For the **Students' endorsement of gender equality scale**, it is clear that two classes are highly similar across countries based on the country individual analysis, Fully egalitarian and Competition-driven sexism class. Both have high probabilities to agree to the positively worded items in the scale. Additionally, for members in the Fully egalitarian class, it is highly likely to agree to the (reversed) negatively worded items in contrast to members of the Competition-driven sexism class that are highly likely to disagree with these items. This is consistent in most countries in which the probability to agree to the first (reversed) negatively worded item is random (0.5), this probability decreases consistently for the next (reversed) negatively worded item. This finding could suggest that an evaluation of the impact of negative wording on the interpretation of these items might be a good idea to disregard possible misunderstandings of the items real meaning. The members of the Non-egalitarian class would highly disagree with all the items even showing stronger disagreement with the (reversed) negatively worded items. Finally, a subpopulation that tends to agree to most of the items in this scale but strongly agrees to the ones related to political equality for women can be observed, it was called Political egalitarian. 



Class sizes cannot be established to be equal in all countries due to failure in achieving complete homogeneity. Even though Fully egalitarian is the predominant class in most countries, particularly in Nordic countries, in some eastern European countries Political egalitarian class has the larger number of members. Moreover, the Non-egalitarian class size in some of these eastern European countries is composed of more than 10% of the population.  



A confirmatory approach for the gender equality scale was performed to give evidence of the strong agreement of the Fully egalitarian class with gender equality based on opportunities in the government. Similarly, it was confirmed the relation that the second-highest probability to agree is shared by two items in the Fully egalitarian class and by one item in the Competitive-driven sexism class equally. More interesting is that students in the Competition-driven sexism class would not have a clear attitude towards equal rights for women in politics.



For the **Students' endorsement of equal rights for all ethnic/racial groups** scale, four classes are found as highly similar across countries, Fully egalitarian, Political non-egalitarian, Employment non-egalitarian and Non-egalitarian. Similarly to the gender equality scale, members of the first class, Fully egalitarian, highly agree to all the items in the global model but when looking at the individual country models the probability to agree to encourage members of all ethnic and racial groups to run in elections is lower compared to the other items, particularly in Belgium (Flemish), Bulgaria, Croatia, Latvia, Lithuania, Netherlands and Slovenia. The members in the Political non-egalitarian class are likely to agree mainly to equality in having a good education and chance to get good jobs for all ethnic and racial groups but less likely to agree to encourage them to run in elections. The members in the Employment non-egalitarian class are unlike to agree that all ethnic and racial groups should have equal chances to get good jobs. And finally, members of the Non-egalitarian class are highly unlikely to agree to any of the items in this scale. 



Considering the class sizes for this scale, comparability can not be granted. It is clear from the partially homogeneous model that the sizes differ greatly from country to country. Particularly, Nordic countries would concentrate most of the population in the Fully egalitarian class, meanwhile, Eastern European countries Political or Employment non-egalitarian classes would concentrate most of the population.  



A confirmatory approach could not be established for this scale as the model fit statistics for the confirmatory model did not provide enough evidence to state that the model was better than the freely estimated model. 



At this point, it is clear that complete comparability is not assured when we look at subpopulation patterns when analyzing Large Scale Assessments. Even though is it confirmed that at a variable level this comparison is straightforward, this does not apply necessary when comparing all different subgroups that can be identified within a country with another. It is still possible to obtain evidence that while most of the profiles are similar across countries the proportion of students that relate to those profiles is not. This result was expected due to cultural background, particularly in countries more open to gender equality and cultural diversity such as Nordic countries and countries with economic challenges such as eastern European countries.  



One of the limitations of this research is the complexity in the computation of some analyses, particularly measurement invariance models. This procedure requires a high amount of computational resources to perform properly due to the multiple models and parameters that should be estimated. This takes much time to perform as more countries are added into the analysis the more complex it gets and in most cases models will not converge or find global maxima. For this reason, a good strategy that allows testing a small number of models is necessary. In this research independent country models were conducted first to identify and select common patterns in the scales that would be proper for the measurement invariance models.  



This research is of great help for researchers that want to perform the same analysis but for comparing different cycles of the study, as was mentioned, these scales are present in the study from 2009 and they will be present in the next cycle of 2022. Measurement invariance has to be tested for cycles using the same scales and countries before comparing. For researchers interested in study other countries, these results can be used for comparative purposes, as well as all the syntax provided with this research that produce the different models and comparisons.  