`r if(knitr:::is_latex_output()) '\\appendix'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 


# Complementary tables  

```{r table1, echo=FALSE, warning=FALSE, message=FALSE, results="asis", fig.cap="left-aligned"}

kbl(table(data_model$IDCNTRY,data_model$YEAR), 
    caption = "Countries sample sizes included in the analysis", label = "tableA1",
    escape = FALSE, booktabs = TRUE, longtable = TRUE) %>% 
  column_spec(1, width = "10em") %>%
  kable_styling(bootstrap_options = c("bordered", "hover"), latex_options = c("repeat_header", "HOLD_position"), 
                position = "left", font_size = 11, full_width = FALSE) %>% print()

```  



```{r table2, eval = FALSE, echo=FALSE, warning=FALSE, message=FALSE, results="asis", fig.cap="left-aligned"}

items99 <-  rbind(
c("WOMRTMLE","Attitudes toward Women’s Political and Economic Rights",""),
c("BS4G1","Women should run for public office [a seat in the legislature] and take part in the government just as men do.",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("BS4G4","Women should have the same rights as men in every way.",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("BS4G6","Women should stay out of politics",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("BS4G9","When jobs are scarce, men [should] have more right to a job than women.",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("BS4G11","Men and women should get equal pay when they are in the same jobs [occupations].",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("BS4G13","Men are better qualified to be political leaders than women.",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")))

colnames(items99) <- c("CIVED 1999",	"Description question",	"Resp categories")

kbl(items99, 
    caption = "Items attitudes towards gender equality. Cived 1999", 
    label = "tableA2",
    escape = FALSE,
    booktabs = TRUE,
    longtable = TRUE) %>% 
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "25em") %>%
  column_spec(3, width = "10em") %>%
  row_spec(c(0,1), bold = TRUE) %>%
  collapse_rows(columns = 3, valign = "middle")  %>% 
  kable_styling(bootstrap_options = c("bordered", "hover"), 
                latex_options = c("repeat_header", "HOLD_position"), 
                position = "left", font_size = 11, full_width = FALSE) 

```

```{r table3, eval = FALSE, echo=FALSE, warning=FALSE, message=FALSE, results="asis", fig.cap="left-aligned"}

items09 <-  rbind(
c("GENEQL","Students’ attitudes toward gender equality",""),
c("IS2P24A","Men and women should have equal opportunities to take part in government",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS2P24B","Men and women should have the same rights in every way ",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS2P24C","Women should stay out of politics",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS2P24D","When there are not many jobs available, men should have more right to a job than women",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS2P24E","Men and women should get equal pay when they are doing the same jobs",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS2P24F","Men are better qualified to be political leaders than women",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")))

colnames(items09) <- c("ICCS 2009",	"Description question",	"Resp categories")

kbl(items09, 
    caption = "Items attitudes towards gender equality. ICCS 2009", 
    label = "tableA3",
    escape = FALSE,
    booktabs = TRUE,
    longtable = TRUE) %>% 
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "25em") %>%
  column_spec(3, width = "10em") %>%
  row_spec(c(0,1), bold = TRUE) %>% 
  collapse_rows(columns = 3, valign = "middle")  %>% 
  kable_styling(bootstrap_options = c("bordered", "hover"), latex_options = c("repeat_header", "HOLD_position"), 
                position = "left", font_size = 11, full_width = FALSE)

```


```{r table4, echo=FALSE, warning=FALSE, message=FALSE, results="asis", fig.cap="left-aligned"}

items16 <-  rbind(
c("S\\_GENEQL","Attitudes toward gender equality",""),
c("IS3G24A","Roles women and men/Men and women should have equal opportunities to take part in government",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS3G24B","Roles women and men/Men and women should have the same rights in every way",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS3G24C","Roles women and men/Women should stay out of politics",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS3G24D","Roles women and men/Not many jobs available, men should have more right to a job than women",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS3G24E","Roles women and men/Men and women should get equal pay when they are doing the same jobs",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS3G24F","Roles women and men/Men are better qualified to be political leaders than women",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")),
c("IS3G24G","Roles women and men/Women’s first priority should be raising children",linebreak("1-Strongly disagree\n2-Disagree\n3-Agree\n4-Strongly agree")))

colnames(items16) <- c("ICCS 2016",	"Description question",	"Resp categories")

kbl(items16, 
    caption = "Items attitudes towards gender equality. ICCS 2016", 
    label = "tableA4",
    escape = FALSE,
    booktabs = TRUE,
    longtable = TRUE) %>% 
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "25em") %>%
  column_spec(3, width = "10em") %>%
  row_spec(c(0,1), bold = TRUE) %>%
  collapse_rows(columns = 3, valign = "middle")  %>% 
  kable_styling(bootstrap_options = c("bordered", "hover"), latex_options = c("repeat_header", "HOLD_position"), 
                position = "left", font_size = 11, full_width = FALSE)

```

# Syntax


**Packages used**

```{r ref.label='include_packages', results='hide', echo = TRUE}
```